Add OpenGL and GTK depenencies.
The rosdep db will need to be updated for these.

With this change the build now fails with

```
In file included from /tmp/binarydeb/ros-crystal-librealsense2-2.16.5/examples/software-device/../example.hpp:7:0,
                 from /tmp/binarydeb/ros-crystal-librealsense2-2.16.5/examples/software-device/rs-software-device.cpp:6:
/usr/include/GLFW/glfw3.h:177:12: fatal error: GL/glu.h: No such file or directory
   #include <GL/glu.h>
            ^~~~~~~~~~
compilation terminated.
```